export const SIGN_IN_SUCCESFULL = 'SIGN_IN_SUCCESFULL'
export const SIGN_IN_REJECTED = 'SIGN_IN_REJECTED'
export const SIGN_OUT = 'SIGN_OUT'

export const FETCH_PROJECT = 'FETCH_PROJECT'
export const FETCH_PROJECT_SUCCEEDED = 'FETCH_PROJECT_SUCCEEDED'
export const FETCH_PROJECT_FAILED = 'FETCH_PROJECT_FAILED'

export const FETCH_SAMPLE_VECTOR = 'FETCH_SAMPLE_VECTOR'
export const FETCH_SAMPLE_VECTOR_SUCCEEDED = 'FETCH_SAMPLE_VECTOR_SUCCEEDED'
export const FETCH_SAMPLE_VECTOR_FAILED = 'FETCH_SAMPLE_VECTOR_FAILED'

export const FETCH_META = 'FETCH_META'
export const FETCH_META_SUCCEEDED = 'FETCH_META_SUCCEEDED'
export const FETCH_META_FAILED = 'FETCH_META_FAILED'
